spring:
  application:
    name: "spring-test-task"

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/medical_task_db
    username: testTaskUser
    password: testTaskPassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080